namespace Rootwire.ApiClients.FreeAgentTests;

public static partial class FreeAgentFixtures
{
  private const string InvoiceListJson = """
                                         {
                                             "invoices": [
                                                 {
                                                     "url": "https://api.sandbox.freeagent.com/v2/invoices/522684",
                                                     "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                     "dated_on": "2024-03-14",
                                                     "due_on": "2024-03-24",
                                                     "reference": "001",
                                                     "currency": "GBP",
                                                     "exchange_rate": "1.0",
                                                     "net_value": "0.0",
                                                     "involves_sales_tax": false,
                                                     "is_interim_uk_vat": false,
                                                     "total_value": "0.0",
                                                     "paid_value": "0.0",
                                                     "due_value": "0.0",
                                                     "status": "Draft",
                                                     "long_status": "Draft",
                                                     "omit_header": false,
                                                     "always_show_bic_and_iban": false,
                                                     "payment_terms_in_days": 10,
                                                     "created_at": "2024-03-14T07:53:14.000Z",
                                                     "updated_at": "2024-03-14T07:53:14.000Z",
                                                     "send_new_invoice_emails": false,
                                                     "send_reminder_emails": false,
                                                     "send_thank_you_emails": false,
                                                     "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                     "payment_methods": {},
                                                     "contact_name": "TESTORG 1 - KEEP THIS"
                                                 },
                                                 {
                                                     "url": "https://api.sandbox.freeagent.com/v2/invoices/522685",
                                                     "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                     "dated_on": "2024-03-14",
                                                     "due_on": "2024-03-24",
                                                     "reference": "d659e78a-540f-4de7-8ae6-3bd0d756b2d1",
                                                     "currency": "GBP",
                                                     "exchange_rate": "1.0",
                                                     "net_value": "0.0",
                                                     "involves_sales_tax": false,
                                                     "is_interim_uk_vat": false,
                                                     "total_value": "0.0",
                                                     "paid_value": "0.0",
                                                     "due_value": "0.0",
                                                     "status": "Draft",
                                                     "long_status": "Draft",
                                                     "omit_header": false,
                                                     "always_show_bic_and_iban": false,
                                                     "payment_terms_in_days": 10,
                                                     "created_at": "2024-03-14T08:07:20.000Z",
                                                     "updated_at": "2024-03-14T08:07:20.000Z",
                                                     "send_new_invoice_emails": false,
                                                     "send_reminder_emails": false,
                                                     "send_thank_you_emails": false,
                                                     "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                     "payment_methods": {},
                                                     "contact_name": "TESTORG 1 - KEEP THIS"
                                                 },
                                                 {
                                                     "url": "https://api.sandbox.freeagent.com/v2/invoices/522691",
                                                     "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                     "dated_on": "2024-03-14",
                                                     "due_on": "2024-03-24",
                                                     "reference": "f1bf7cf3-a271-435d-aa28-66cdb169b705",
                                                     "currency": "GBP",
                                                     "exchange_rate": "1.0",
                                                     "net_value": "0.0",
                                                     "involves_sales_tax": false,
                                                     "is_interim_uk_vat": false,
                                                     "total_value": "0.0",
                                                     "paid_value": "0.0",
                                                     "due_value": "0.0",
                                                     "discount_value": "0.0",
                                                     "status": "Draft",
                                                     "long_status": "Draft",
                                                     "comments": "Test Invoice Comment",
                                                     "discount_percent": "1.5",
                                                     "omit_header": false,
                                                     "always_show_bic_and_iban": false,
                                                     "payment_terms_in_days": 10,
                                                     "created_at": "2024-03-14T08:13:49.000Z",
                                                     "updated_at": "2024-03-14T08:13:49.000Z",
                                                     "send_new_invoice_emails": false,
                                                     "send_reminder_emails": false,
                                                     "send_thank_you_emails": false,
                                                     "client_contact_name": "Test Client Contact Name",
                                                     "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                     "payment_methods": {},
                                                     "contact_name": "TESTORG 1 - KEEP THIS"
                                                 },
                                                 {
                                                     "url": "https://api.sandbox.freeagent.com/v2/invoices/522694",
                                                     "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                     "dated_on": "2024-03-14",
                                                     "due_on": "2024-03-24",
                                                     "reference": "8300ff82-ff53-4f57-80d0-1248975fddf3",
                                                     "currency": "GBP",
                                                     "exchange_rate": "1.0",
                                                     "net_value": "31.03",
                                                     "involves_sales_tax": false,
                                                     "is_interim_uk_vat": false,
                                                     "total_value": "31.03",
                                                     "paid_value": "0.0",
                                                     "due_value": "31.03",
                                                     "discount_value": "0.47",
                                                     "status": "Draft",
                                                     "long_status": "Draft",
                                                     "comments": "Test Invoice Comment",
                                                     "discount_percent": "1.5",
                                                     "po_reference": "Test PO Reference",
                                                     "omit_header": true,
                                                     "always_show_bic_and_iban": true,
                                                     "payment_terms_in_days": 10,
                                                     "created_at": "2024-03-14T08:22:10.000Z",
                                                     "updated_at": "2024-03-14T08:22:10.000Z",
                                                     "send_new_invoice_emails": false,
                                                     "send_reminder_emails": false,
                                                     "send_thank_you_emails": false,
                                                     "payment_terms": "Custom Payment Terms Test",
                                                     "client_contact_name": "Test Client Contact Name",
                                                     "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                     "payment_methods": {},
                                                     "contact_name": "TESTORG 1 - KEEP THIS"
                                                 },
                                                 {
                                                     "url": "https://api.sandbox.freeagent.com/v2/invoices/522695",
                                                     "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                     "dated_on": "2024-03-14",
                                                     "due_on": "2024-03-24",
                                                     "reference": "6f0a0cb4-818c-44a1-9f4c-5151f25b5d61",
                                                     "currency": "GBP",
                                                     "exchange_rate": "1.0",
                                                     "net_value": "79.25",
                                                     "involves_sales_tax": false,
                                                     "is_interim_uk_vat": false,
                                                     "total_value": "79.25",
                                                     "paid_value": "0.0",
                                                     "due_value": "79.25",
                                                     "discount_value": "1.21",
                                                     "status": "Draft",
                                                     "long_status": "Draft",
                                                     "comments": "Test Invoice Comment",
                                                     "discount_percent": "1.5",
                                                     "po_reference": "Test PO Reference",
                                                     "omit_header": true,
                                                     "always_show_bic_and_iban": true,
                                                     "payment_terms_in_days": 10,
                                                     "created_at": "2024-03-14T08:33:43.000Z",
                                                     "updated_at": "2024-03-14T08:33:43.000Z",
                                                     "send_new_invoice_emails": false,
                                                     "send_reminder_emails": false,
                                                     "send_thank_you_emails": false,
                                                     "payment_terms": "Custom Payment Terms Test",
                                                     "client_contact_name": "Test Client Contact Name",
                                                     "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                     "payment_methods": {},
                                                     "contact_name": "TESTORG 1 - KEEP THIS"
                                                 }
                                             ]
                                         }
                                         """;

  private const string InvoiceItemJson = """
                                           {
                                               "invoice": {
                                                   "url": "https://api.sandbox.freeagent.com/v2/invoices/522695",
                                                   "contact": "https://api.sandbox.freeagent.com/v2/contacts/151730",
                                                   "dated_on": "2024-03-14",
                                                   "due_on": "2024-03-24",
                                                   "reference": "6f0a0cb4-818c-44a1-9f4c-5151f25b5d61",
                                                   "currency": "GBP",
                                                   "exchange_rate": "1.0",
                                                   "net_value": "79.25",
                                                   "involves_sales_tax": false,
                                                   "is_interim_uk_vat": false,
                                                   "total_value": "79.25",
                                                   "paid_value": "0.0",
                                                   "due_value": "79.25",
                                                   "discount_value": "1.21",
                                                   "status": "Draft",
                                                   "long_status": "Draft",
                                                   "comments": "Test Invoice Comment",
                                                   "discount_percent": "1.5",
                                                   "po_reference": "Test PO Reference",
                                                   "omit_header": true,
                                                   "always_show_bic_and_iban": true,
                                                   "payment_terms_in_days": 10,
                                                   "created_at": "2024-03-14T08:33:43.000Z",
                                                   "updated_at": "2024-03-14T08:33:43.000Z",
                                                   "send_new_invoice_emails": false,
                                                   "send_reminder_emails": false,
                                                   "send_thank_you_emails": false,
                                                   "payment_terms": "Custom Payment Terms Test",
                                                   "client_contact_name": "Test Client Contact Name",
                                                   "bank_account": "https://api.sandbox.freeagent.com/v2/bank_accounts/29863",
                                                   "payment_methods": {},
                                                   "contact_name": "TESTORG 1 - KEEP THIS",
                                                   "invoice_items": [
                                                       {
                                                           "url": "https://api.sandbox.freeagent.com/v2/invoice_items/869351",
                                                           "position": 1,
                                                           "description": "Test Invoice Item 1",
                                                           "price": "10.5",
                                                           "quantity": "3.0",
                                                           "suffers_cis_deduction": false,
                                                           "category": "https://api.sandbox.freeagent.com/v2/categories/002"
                                                       },
                                                       {
                                                           "url": "https://api.sandbox.freeagent.com/v2/invoice_items/869352",
                                                           "position": 2,
                                                           "description": "Test Invoice Item 2",
                                                           "price": "1.53",
                                                           "quantity": "32.0",
                                                           "suffers_cis_deduction": false,
                                                           "category": "https://api.sandbox.freeagent.com/v2/categories/002"
                                                       }
                                                   ]
                                               }
                                           }
                                           """;
}